### ISSUE TITLE
Style Dictionary blindspots

### ISSUE THREAD

**Issue by fleven-kds** [kickstartDS/kickstartDS#1610]
## Issues:

When implementing designs using the style dictionary, certain limitations were encountered, specifically in applying styles to:

- Distinct `text-color` for Headline and Copy
- `background-color` for bold elements
- Semantic token for `color-secondary`

These issues stem from systematic limitations:

- Branding Initialization Limitations: The semantic token layer is lacking important categories (one example would be the afformentioned copy/headline text-color)
- Inflexibility in Semantic Token Generation: The initial setup allows only for the addition of color scales without further semantic differentiation (e.g., `background-color`, `text-color`). A manually added `color-secondary` cannot have a semantic `background-color` token associated with it. 

Furthermore there are some questionable default values in the the branding initialisation:
- `background-color` token  used in the seciton component (accent) should not be `alpha` values as they might mix with the browser background, creating unpredictable outcomes
- there shouldnt be any `transparent` values unless the semantic token describes it as such (currently `background-color-interface-interactive`)

## TODOS:

- [x] ALL color token get a semantic token set (border-color, background-color, text-color)
- [x] ALL semantic color token get the same sub-categories (interactive > active, selected etc..)
- [x] remove visited token under text-color
- [x] add copy & display text-color token, they will only have semantic text-color token

```
text-color-copy: var(--ks-color-fg-alpha-3)
text-color-copy-interactive: var(--ks-link-color)
text-color-copy-interactive-hover: var(--ks-color-link-to-fg-2)
text-color-copy-interactive-active: var(--ks-color-link-to-fg-3)
text-color-copy-interactive-selected: var(--ks-color-link-to-fg-3)
```

```
text-color-display: var(--ks-color-fg)
text-color-display-interactive: var(--ks-color-link)
text-color-display-interactive-hover: var(--ks-color-link-to-fg-2)
text-color-display-interactive-active: var(--ks-color-link-to-fg-3)
text-color-display-interactive-selected: var(--ks-color-link-to-fg-3)
```

- [x] replace `alpha` with `to-bg` in background-color-accent & -bold
- [x] change the default value of background-color-interface-interactive to var(--ks-color-fg-alpha-8)
- [x] Add `to-fg` scale to color token
- [x] change the init prompts to the following:

```
"background": "#06081F",
"background-inverted": "#f1f1f3",
"foreground": "#fff",
"foreground-inverted": "#06081F",
```

- [x] adjust box-shadow token as referenced in comment
- [x] add semantic category `card` (`text-color`, `background-color`, `border-color`)

**Comment by fleven-kds** [comment]
Furthermore, we need to separate bg & fg-inverted (vice versa fg & bg-inverted) in the token initialisation.
The init prompts should look something like this:

```
"background": "#06081F",
"background-inverted": "#f1f1f3",
"foreground": "#fff",
"foreground-inverted": "#06081F",
```

**Comment by fleven-kds** [comment]
The box shadow color isnt affected by the inverte system as it is a direct rbg value in there.
My proposal is adding inverted box-shadow token:

```
{
  "ks": {
    "box-shadow": {
      "opacity": {
        "control": {
         XXX
        },
        "control-inverted": {
         XXX
        },
        "card": {
         XXX
        },
        "card-inverted": {
         XXX
        },
        "surface": {
         XXX
        },
        "surface-inverted": {
         XXX
        }
      },
      "color": {
        "control": {
         XXX
        },
        "control-inverted": {
         XXX
        },
        "card": {
         XXX
        },
        "card-inverted": {
         XXX
        },
        "surface": {
         XXX
        },
        "surface-inverted": {
         XXX
        }
      },
      "control": {
        XXX
      },
      "control-inverted": {
        XXX
      },
      "card": {
        XXX
      },
      "card-inverted": {
        XXX
      },
      "surface": {
        XXX
      },
      "surface-inverted": {
        XXX
      }
    }
  }
}
```

**Comment by fleven-kds** [comment]
Do we need an additional card category, as differs quite a bit form most interface elements?

**Comment by fleven-kds** [comment]
We should discuss the possibility of going darker and lighter in the color scales

**Comment by fleven-kds** [comment]
Is it possible to remove the `attributes` data from the user token file?

**Comment by fleven-kds** [comment]
Can we add a toggle to the branding init that determines wether a color is considered light or dark?

**Comment by lmestel** [comment]
:rocket: Issue was released in  :rocket:
